BEGIN TRANSACTION;
CREATE TABLE Benutzer (
benutzerID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
Vorname TEXT NOT NULL,
Nachname TEXT NOT NULL,
Benutzername TEXT NOT NULL UNIQUE
);
CREATE TABLE Spiele (
spielID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
creator INTEGER NOT NULL,
joiner INTEGER,
FOREIGN KEY(creator) REFERENCES Benutzer(benutzerID),
FOREIGN KEY(joiner) REFERENCES Benutzer(benutzerID)
);

COMMIT;